[package]
name = "dmytro/combat-system"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Red = "red-blox/red@^2.0.0-rc.7"
Trove = "sleitnick/trove@0.5.0"